### ISSUE TITLE
properly configuration for user based setting 

### ISSUE THREAD

**Issue by Busuzima** [akaunting/setting#49]
Hi,

i've read the documentation and wanted to try out the package but i'm not sure on how to configure it properly, the only thing that i saw in readme is that i need to add this:
setting()->setExtraColumns(['user_id' => Auth::user()->id]);
but i don't need to update also the migration file with the new column for settings table?
should ialso specifi in setting.php config file the new user_id field?

i've tried also to look in the net but nothing popup to my eyes, so if someone have a more complete and deep tutorial it would be great.

Thanks

**Comment by denisdulici** [comment]
Yes, this is enough `setting()->setExtraColumns(['user_id' => auth()->user()->id]);`

**Comment by spadom** [comment]
i've put setting()->setExtraColumns(['user_id' => auth()->user()->id]); in middleware and setting() helper function work well, problem is when i have to override config default function because it doesn't find user_id, where can i put the setting()->setExtraColumns(['user_id' => auth()->user()->id]); in order to let it read from config function?
