### ISSUE TITLE
Setting does not save value

### ISSUE THREAD

**Issue by BaiMaoLi** [akaunting/setting#59]
**This is my code to save setting**
setting(['access_token',$user->access_token]) 

here $user->access_token is not null and i've checked that.
But setting is not being saved into my database.
What is issue here?

settings.php
 'driver'           => 'database',

**Comment by BahaStriker** [comment]
use \Setting::save(); after \Setting::set()

**Comment by gadnis** [comment]
For me also not working..

`setting()->set('default.currency', 'EUR');`
`setting()->save();`

And the database is empty.

config/app.php
` 'providers' => [ ...`
`Akaunting\Setting\Provider::class,`

php artisan migrate - done

Laravel 5.4
PHP 7.2

**Comment by gadnis** [comment]
so in my case:

file: `Akaunting\Setting\Contracts\Driver` 
function `public function set($key, $value = null)`
on line `76` - `if (!$this->checkExtraColumns()) { return; }` hapen "return" 😁

It is because I use `required_extra_columns` in `config/setting.php:98`

That means, before setting any value, I must `setExtraColumns`, for example:

`setting()->setExtraColumns([ 'user_id' => 1, 'connection_id' => 123 ]`
`setting()->set('default.currrency', 'EUR');`

and it works, date is on DB :) Hope for some one will be helpful 😁

@BaiMaoLi

**Comment by denisdulici** [comment]
Yes, if you should set the required columns first, that's the purpose of that field in config.
